{"name": "Вход невозможен c несуществующей парой логин-пароль", "status": "passed", "start": 1703500270192, "stop": 1703500270680, "uuid": "613791cd-e362-4a5a-b457-5a9320317880", "historyId": "f520316220b0ec5a8f6ad13308445769", "testCaseId": "f520316220b0ec5a8f6ad13308445769", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_fail_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-R8S2KV9"}, {"name": "thread", "value": "14488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}